### ISSUE TITLE
How to run with visual studio?

### ISSUE THREAD

**Issue by AliKhadivi** [loyldg/mytelegram#11]
![image](https://user-images.githubusercontent.com/74895885/202270893-c57e3536-385f-4f71-9585-8dba244e002d.png)
I ran it with visual studio but no port is open

![image](https://user-images.githubusercontent.com/74895885/202271859-a4b89f1a-f1ab-4d93-919a-3ea7a9fde4cf.png)
Where are the source code of these projects?

**Comment by AliKhadivi** [comment]
![image](https://user-images.githubusercontent.com/74895885/202273291-a5e963a1-35d9-4462-a18e-7a8a7f075623.png)
or this

**Comment by loyldg** [comment]
Those servers are not open source yet(auth,file,gateway,seq,session),if you want to run with visual studio

1. Download the latest servers from https://github.com/loyldg/mytelegram/releases/download/v0.11.1102/mytelegram-server-0.11.1102-win-x64.zip
2. Run start-all.bat
3. Kill process Mytelegram.Messenger.Abp.exe
4. Start MyTelegram.Messenger.Abp from visual studio

**Comment by ti-bone** [comment]
@loyldg Are that servers will be open-source?
