### ISSUE TITLE
Secret chats and authKeyId 00 error

### ISSUE THREAD

**Issue by AlessandroZanatta** [loyldg/mytelegram#13]
Hi,

I'm trying to make a server work locally for research purposes. I'd like to know if this server implements secret chats or not.

Moreover, every time my client connects it gets a `remove disconnected session failed,can not find authKeyId 00` error, and I cannot find references in the code to pinpoint the root cause.

Your help would be very appreciated, thanks!

**Comment by loyldg** [comment]
Only pro version support secret chats
Open source version only support the following features:
- Private chat
- Group chat
- Supergroup chat
- Channel

**Comment by loyldg** [comment]
The demo server(pro)  implements secret chats,you can try it
