### ISSUE TITLE
No Sms - Android Client

### ISSUE THREAD

**Issue by SakonLight90** [loyldg/mytelegram#14]
Hello, The server goes online but cant receive sms for verify with the configured android client

**Comment by loyldg** [comment]
The default code for demo server is `22222` ,and will not send the code using SMS.
If you use your own server,you need to set the Twilio parameters
start-all.ps1
```
$env:TwilioSms__Enabled=true
$env:TwilioSms__AccountSId=
$env:TwilioSms__AuthToken=
$env:TwilioSms__FromNumber=
```
start-all.bat
```
set TwilioSms__Enabled=true
set TwilioSms__AccountSId=
set TwilioSms__AuthToken=
set TwilioSms__FromNumber=
```
start-all.sh
```
export TwilioSms__Enabled=true
export TwilioSms__AccountSId=
export TwilioSms__AuthToken=
export TwilioSms__FromNumber=
```
