### ISSUE TITLE
System.NotSupportedException: Unsupported constructorId:0xad253d78

### ISSUE THREAD

**Issue by Clownsw** [loyldg/mytelegram#16]
![捕获](https://user-images.githubusercontent.com/28394742/222937761-ad2551a1-e1d9-4b9f-bda5-8ebff6daa7b0.PNG)

**Comment by loyldg** [comment]
From the screenshot,you deployed mytelegram server using docker image,but docker image has not been updated to the latest version,you can use [MyTelegram server for win-x64 v0.12.304](https://github.com/loyldg/mytelegram/releases/download/v0.12.304/mytelegram-server-0.12.304-win-x64.zip) or use this client [Telegram-4.2.2-x64](https://github.com/loyldg/mytelegram/releases/download/v0.11.1102/Telegram-4.2.2-x64.zip)
