### ISSUE TITLE
How can I grant administrator rights?

### ISSUE THREAD

**Issue by BROILYA091** [loyldg/mytelegram#17]
Does the server have admin rights on the server and how do I get them?

**Comment by loyldg** [comment]
The server runs with normal user permissions

**Comment by BROILYA091** [comment]
And how to run it in the elevated rights mode?

**Comment by loyldg** [comment]
The server actually does not require administrator rights. If you really need to run the server with administrator rights

- On windows platform:Right-click start-all.bat, and then click Run as administrator  
- On linux platform:Log in as root user and run start-all.sh
