### ISSUE TITLE
可以完善下客户端webK的文档吗

### ISSUE THREAD

**Issue by ChenMoGe2** [loyldg/mytelegram#5]
你好，非常感谢开源这个项目。我现在在编译web k的相关代码，目前文档中只标注了在哪个文件进行修改，但没有像webz那样具体到行。可以麻烦完善下这里吗谢谢。

另外，webz我是按照文档编译的，官方貌似只有npm run dev这一种启动方式，如果我想把项目放在生产环境到nginx怎么实现呢？谢谢！

**Comment by loyldg** [comment]
WebK的编译步骤,后面我会尽量写得详细一点.

> 另外，webz我是按照文档编译的，官方貌似只有npm run dev这一种启动方式，如果我想把项目放在生产环境到nginx怎么实现呢？谢谢！  

可以执行命令`npm run build`或者`yarn build`,package.json里还有其他命令,你可以看一下,执行后会在dist目录里生成相关文件,把dist目录里的内容放到你的网站目录就可以了

**Comment by ChenMoGe2** [comment]
> WebK的编译步骤,后面我会尽量写得详细一点.
> 
> > 另外，webz我是按照文档编译的，官方貌似只有npm run dev这一种启动方式，如果我想把项目放在生产环境到nginx怎么实现呢？谢谢！
> 
> 可以执行命令`npm run build`或者`yarn build`,package.json里还有其他命令,你可以看一下,执行后会在dist目录里生成相关文件,把dist目录里的内容放到你的网站目录就可以了

好的 感谢！
