### ISSUE TITLE
webz版接收到视频文件后，下载视频报404错误

### ISSUE THREAD

**Issue by ChenMoGe2** [loyldg/mytelegram#7]
你好，我用webz版改好服务器和公钥后进行登录，并添加好友。两个人对话的时候，接收方收到视频后无法下载，我查看控制台会有一个请求https://10.8.0.1:11236/progressive/msg1560100594-3240:6154291039671682263 404 Not found。我连接TG的服务器也会报这个错误，请问这个问题怎么解决。谢谢

**Comment by loyldg** [comment]
目前MyTelegram与Web客户端的通信是Websocket协议,上面的404错误应该不会影响文件接收,你可以试一下发图片或者发其他文件,看能不能接收到.并且检查一下MyTelegram的各个服务器是否有报错

**Comment by ChenMoGe2** [comment]
> 目前MyTelegram与Web客户端的通信是Websocket协议,上面的404错误应该不会影响文件接收,你可以试一下发图片或者发其他文件,看能不能接收到.并且检查一下MyTelegram的各个服务器是否有报错

图片是可以收到的，服务器貌似没看到错误，这个错误目前只有下载视频的时候会发生。我看官方上也有人遇到同样的情况。[https://github.com/Ajaxy/telegram-tt/issues/153](url)

**Comment by loyldg** [comment]
那这个估计是WebZ客户端的Bug，需要到WebZ那边进行反馈

**Comment by ChenMoGe2** [comment]
> 那这个估计是WebZ客户端的Bug，需要到WebZ那边进行反馈

好的谢谢
