### ISSUE TITLE
Where are the Dockerfiles?

### ISSUE THREAD

**Issue by AliKhadivi** [loyldg/mytelegram#9]

**Comment by loyldg** [comment]
If you want to use Docker to build MyTelegramServer, you can use https://github.com/loyldg/mytelegram/blob/dev/source/src/MyTelegram.MessengerServer.Abp/Dockerfile. 
If you want to run the docker image, you can follow this https://github.com/loyldg/mytelegram#run-mytelegram-server-with-docker

**Comment by AliKhadivi** [comment]
Thank you
